name: Deploy UPOD-WEB ReactJS

on:
  push:
    branches:
      - main

env: 
    IMAGE_TAG: "latest"
    IMAGE: "upod.api"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Connect to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/$IMAGE:$IMAGE_TAG .

      - name: Push Docker image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/$IMAGE:$IMAGE_TAG